# generated by datamodel-codegen:
#   filename:  judgment.schema.json
#   timestamp: 2026-08-02T05:07:01+00:00

from __future__ import annotations

from enum import StrEnum
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, confloat, conint, constr


class Verdict(StrEnum):
    succeeded = 'succeeded'
    in_progress = 'in_progress'
    failed = 'failed'
    indeterminate = 'indeterminate'


class Bbox(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    x: float
    y: float
    w: confloat(ge=0.0)
    h: confloat(ge=0.0)


class ObservedObject(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    object_id: constr(min_length=1)
    confidence: confloat(ge=0.0, le=1.0)
    bbox: Bbox | None = None


class Method(StrEnum):
    instrument = 'instrument'
    display_readout = 'display_readout'
    operator_attested = 'operator_attested'
    visual_estimate = 'visual_estimate'


class MeasuredUnit(StrEnum):
    s = 's'
    min = 'min'
    h = 'h'
    c = 'C'
    k = 'K'
    u_l = 'uL'
    m_l = 'mL'
    l = 'L'
    ug = 'ug'
    mg = 'mg'
    g = 'g'
    kg = 'kg'
    nm = 'nm'
    um = 'um'
    mm = 'mm'
    cm = 'cm'
    m = 'm'
    m_1 = 'M'
    m_m = 'mM'
    u_m = 'uM'
    mg_per_m_l = 'mg_per_mL'
    rpm = 'rpm'
    g_force = 'g_force'
    pa = 'Pa'
    k_pa = 'kPa'
    bar = 'bar'
    psi = 'psi'
    percent = 'percent'
    p_h = 'pH'
    count = 'count'


class Criterion(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    criterion_index: conint(ge=0, le=9007199254740991)
    satisfied: bool
    evidence: constr(min_length=1)
    method: Method | None = None
    measured_value: float | None = None
    measured_unit: MeasuredUnit | None = None


class Failure(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: constr(min_length=1)
    description: constr(min_length=1)


class Model(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    judgment_id: UUID
    session_id: UUID
    step_id: constr(min_length=1)
    frame_uri: constr(min_length=1)
    emitted_at: AwareDatetime
    source: constr(min_length=1)
    verdict: Verdict
    rationale: constr(min_length=1)
    observed_objects: list[ObservedObject]
    criteria: list[Criterion]
    failure: Failure | None = None
