# generated by datamodel-codegen:
#   filename:  protocol.schema.json
#   timestamp: 2026-08-02T05:07:01+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, confloat, conint, constr


class ExpectedObject(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    object_id: (
        constr(pattern=r'^object:[a-z0-9][a-z0-9_-]*$')
        | constr(pattern=r'^surface:[a-z0-9][a-z0-9_-]*$')
        | constr(pattern=r'^tool:[a-z0-9][a-z0-9_-]*$')
        | constr(pattern=r'^reagent:[a-z0-9][a-z0-9_-]*$')
    )
    label: constr(min_length=1)
    optional: bool


class ExpectedAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    action_id: constr(pattern=r'^action:[a-z0-9][a-z0-9_-]*$')
    label: constr(min_length=1)
    target_object_id: constr(pattern=r'^object:[a-z0-9][a-z0-9_-]*$') | None = None
    instrument_id: (
        constr(pattern=r'^object:[a-z0-9][a-z0-9_-]*$')
        | constr(pattern=r'^tool:[a-z0-9][a-z0-9_-]*$')
        | None
    ) = None


class SuccessCriteria(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['object_on_surface']
    object_id: constr(pattern=r'^object:[a-z0-9][a-z0-9_-]*$')
    surface_id: constr(pattern=r'^surface:[a-z0-9][a-z0-9_-]*$')
    description: constr(min_length=1)


class SuccessCriteria1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['liquid_in_object']
    container_id: constr(pattern=r'^object:[a-z0-9][a-z0-9_-]*$')
    fill_fraction: confloat(ge=0.0, le=1.0) | None = None
    description: constr(min_length=1)


class SuccessCriteria2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['component_added']
    container_id: constr(pattern=r'^object:[a-z0-9][a-z0-9_-]*$')
    component_id: constr(pattern=r'^object:[a-z0-9][a-z0-9_-]*$') | constr(
        pattern=r'^reagent:[a-z0-9][a-z0-9_-]*$'
    )
    description: constr(min_length=1)


class SuccessCriteria3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['action_performed']
    action_id: constr(pattern=r'^action:[a-z0-9][a-z0-9_-]*$')
    target_object_id: constr(pattern=r'^object:[a-z0-9][a-z0-9_-]*$') | None = None
    instrument_id: (
        constr(pattern=r'^object:[a-z0-9][a-z0-9_-]*$')
        | constr(pattern=r'^tool:[a-z0-9][a-z0-9_-]*$')
        | None
    ) = None
    min_count: conint(le=9007199254740991, gt=0) | None = None
    description: constr(min_length=1)


class Unit(StrEnum):
    s = 's'
    min = 'min'
    h = 'h'
    c = 'C'
    k = 'K'
    u_l = 'uL'
    m_l = 'mL'
    l = 'L'
    ug = 'ug'
    mg = 'mg'
    g = 'g'
    kg = 'kg'
    nm = 'nm'
    um = 'um'
    mm = 'mm'
    cm = 'cm'
    m = 'm'
    m_1 = 'M'
    m_m = 'mM'
    u_m = 'uM'
    mg_per_m_l = 'mg_per_mL'
    rpm = 'rpm'
    g_force = 'g_force'
    pa = 'Pa'
    k_pa = 'kPa'
    bar = 'bar'
    psi = 'psi'
    percent = 'percent'
    p_h = 'pH'
    count = 'count'


class SuccessCriteria4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['measurement_in_range']
    quantity: constr(pattern=r'^[a-z][a-z0-9_]*$')
    unit: Unit
    min: float | None = None
    max: float | None = None
    description: constr(min_length=1)


class Kind(StrEnum):
    missing_object = 'missing_object'
    wrong_object = 'wrong_object'
    wrong_surface = 'wrong_surface'
    wrong_order = 'wrong_order'
    spill = 'spill'
    out_of_range = 'out_of_range'
    safety_violation = 'safety_violation'
    other = 'other'


class FailureMode(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Kind
    description: constr(min_length=1)
    references: (
        list[
            constr(pattern=r'^object:[a-z0-9][a-z0-9_-]*$')
            | constr(pattern=r'^surface:[a-z0-9][a-z0-9_-]*$')
            | constr(pattern=r'^tool:[a-z0-9][a-z0-9_-]*$')
            | constr(pattern=r'^reagent:[a-z0-9][a-z0-9_-]*$')
        ]
        | None
    ) = None


class Step(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    step_id: constr(min_length=1)
    order: conint(ge=0, le=9007199254740991)
    title: constr(min_length=1)
    instruction: constr(min_length=1)
    expected_objects: list[ExpectedObject] = Field(..., min_length=1)
    expected_action: ExpectedAction
    success_criteria: list[
        SuccessCriteria
        | SuccessCriteria1
        | SuccessCriteria2
        | SuccessCriteria3
        | SuccessCriteria4
    ] = Field(..., min_length=1)
    failure_modes: list[FailureMode]
    safety_notes: list[constr(min_length=1)]


class Model(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocol_id: constr(min_length=1)
    protocol_version: constr(pattern=r'^\d+\.\d+\.\d+(?:-[\w.-]+)?$')
    name: constr(min_length=1)
    description: str | None = None
    modules: list[constr(min_length=1)]
    steps: list[Step] = Field(..., min_length=1)
