# generated by datamodel-codegen:
#   filename:  session-event.schema.json
#   timestamp: 2026-08-02T05:07:01+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Literal
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, RootModel, constr


class Model1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['step_started']
    at: AwareDatetime
    step_id: constr(min_length=1)


class Model2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['frame_captured']
    at: AwareDatetime
    step_id: constr(min_length=1)
    frame_uri: constr(min_length=1)
    sensor_snapshot_uri: str | None = None


class Model3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['judgment_emitted']
    at: AwareDatetime
    step_id: constr(min_length=1)
    judgment_id: UUID


class Model4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['step_completed']
    at: AwareDatetime
    step_id: constr(min_length=1)
    succeeded: bool


class Model5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['operator_note']
    at: AwareDatetime
    text: constr(min_length=1)


class Unit(StrEnum):
    s = 's'
    min = 'min'
    h = 'h'
    c = 'C'
    k = 'K'
    u_l = 'uL'
    m_l = 'mL'
    l = 'L'
    ug = 'ug'
    mg = 'mg'
    g = 'g'
    kg = 'kg'
    nm = 'nm'
    um = 'um'
    mm = 'mm'
    cm = 'cm'
    m = 'm'
    m_1 = 'M'
    m_m = 'mM'
    u_m = 'uM'
    mg_per_m_l = 'mg_per_mL'
    rpm = 'rpm'
    g_force = 'g_force'
    pa = 'Pa'
    k_pa = 'kPa'
    bar = 'bar'
    psi = 'psi'
    percent = 'percent'
    p_h = 'pH'
    count = 'count'


class Method(StrEnum):
    instrument = 'instrument'
    display_readout = 'display_readout'
    operator_attested = 'operator_attested'
    visual_estimate = 'visual_estimate'


class Model6(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['measurement_recorded']
    at: AwareDatetime
    step_id: constr(min_length=1)
    quantity: constr(pattern=r'^[a-z][a-z0-9_]*$')
    value: float
    unit: Unit
    method: Method
    instrument_id: constr(min_length=1) | None = None


class Status(StrEnum):
    pending = 'pending'
    active = 'active'
    completed = 'completed'
    abandoned = 'abandoned'
    errored = 'errored'


class Model7(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['session_finalized']
    at: AwareDatetime
    status: Status


class Model(RootModel[Model1 | Model2 | Model3 | Model4 | Model5 | Model6 | Model7]):
    root: Model1 | Model2 | Model3 | Model4 | Model5 | Model6 | Model7
