# generated by datamodel-codegen:
#   filename:  session.schema.json
#   timestamp: 2026-08-02T05:07:01+00:00

from __future__ import annotations

from enum import StrEnum
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, constr


class Status(StrEnum):
    pending = 'pending'
    active = 'active'
    completed = 'completed'
    abandoned = 'abandoned'
    errored = 'errored'


class Model(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    session_id: UUID
    protocol_id: constr(min_length=1)
    protocol_version: constr(min_length=1)
    device_adapter_id: constr(min_length=1)
    operator_id: str | None = None
    started_at: AwareDatetime
    ended_at: AwareDatetime | None = None
    status: Status
    tags: list[constr(min_length=1)]
