import type { LabosAgentRole } from "./types.js";

export const LABOS_AGENT_ROLES: LabosAgentRole[] = [
  {
    id: "manager",
    name: "Manager / Planner Agent",
    lane: "cross_cutting",
    purpose: "Decompose objectives into protocol, perception, execution, documentation, and training/eval work.",
    responsibilities: [
      "Create auditable execution plans",
      "Select which specialist agents and tools should run",
      "Maintain task state and escalation policy",
    ],
    inputs: ["objective", "protocol metadata", "available tools", "run constraints"],
    outputs: ["agent plan", "stage exit criteria", "missing capability list"],
    implementationStatus: "partial",
    currentImplementation: ["Kitchen protocol state machine", "multiscale validation plan route"],
    gaps: ["No persisted agent task graph", "No autonomous tool routing loop", "No memory/template library"],
  },
  {
    id: "developer",
    name: "Developer / Execution Agent",
    lane: "digital_lab",
    purpose: "Execute computational steps such as scripts, data transforms, evaluations, and report generation.",
    responsibilities: [
      "Run deterministic code-backed tasks",
      "Prepare datasets and artifacts",
      "Bridge dashboard exports to training/eval workflows",
    ],
    inputs: ["planned task", "dataset paths", "tool capability registry"],
    outputs: ["artifacts", "logs", "metrics"],
    implementationStatus: "partial",
    currentImplementation: ["Inference provider registry", "RunPod provider checks", "training repo split"],
    gaps: ["No LabOS-owned task runner", "No durable execution logs for agent tasks"],
  },
  {
    id: "critic",
    name: "Critic / QA Agent",
    lane: "cross_cutting",
    purpose: "Evaluate intermediate outputs, detect weak evidence, and decide whether to retry, escalate, or accept.",
    responsibilities: [
      "Check schema validity and confidence",
      "Compare teacher/student judgments",
      "Gate advancement and dataset inclusion",
    ],
    inputs: ["model outputs", "protocol criteria", "evidence records"],
    outputs: ["accept/retry/escalate decision", "quality notes", "training labels"],
    implementationStatus: "partial",
    currentImplementation: ["Teacher judgment schema validation", "multiscale evidence aggregation", "route tests"],
    gaps: ["No general critic loop across non-kitchen tasks", "No rubric-based evaluator for full video sessions"],
  },
  {
    id: "toolsmith",
    name: "Tool Creation Agent",
    lane: "digital_lab",
    purpose: "Discover, test, and register new analysis tools into a shared Tool Ocean.",
    responsibilities: [
      "Identify tool gaps",
      "Propose safe wrappers",
      "Validate tools before registration",
    ],
    inputs: ["gap analysis", "literature/API references", "test fixtures"],
    outputs: ["tool spec", "wrapper", "validation report"],
    implementationStatus: "missing",
    currentImplementation: ["LabClaw skill browser only"],
    gaps: ["No automated tool creation", "No sandboxed tool validation", "No Tool Ocean registry persistence"],
  },
  {
    id: "perception",
    name: "Perception / VLM Agent",
    lane: "physical_lab",
    purpose: "Interpret egocentric frames and short video chunks against protocol state.",
    responsibilities: [
      "Run frame, short-chunk, and step-window checks",
      "Detect deviations and hazards",
      "Provide evidence for protocol advancement",
    ],
    inputs: ["camera frames", "video chunks", "protocol step criteria"],
    outputs: ["structured visual evidence", "deviation flags", "confidence"],
    implementationStatus: "partial",
    currentImplementation: ["Frame capture", "Gemini ER video chunks", "multiscale validation WIP"],
    gaps: ["No continuous validation scheduler", "No trained local LabOS VLM yet", "No full-session alignment benchmark"],
  },
  {
    id: "protocol",
    name: "Protocol Agent",
    lane: "physical_lab",
    purpose: "Own protocol definitions, step state, adherence logic, and next-action guidance.",
    responsibilities: [
      "Load or generate protocols",
      "Map observations to protocol steps",
      "Maintain state transitions and recovery paths",
    ],
    inputs: ["protocol", "step evidence", "operator actions"],
    outputs: ["current step", "next step", "adherence/deviation state"],
    implementationStatus: "partial",
    currentImplementation: ["Built-in kitchen protocols", "video-to-protocol endpoint", "protocol tracker"],
    gaps: ["No generic protocol ontology", "No step segment alignment store", "No recovery policy per deviation type"],
  },
  {
    id: "documentarian",
    name: "Documentarian / Memory Agent",
    lane: "cross_cutting",
    purpose: "Persist runs, evidence, summaries, and reusable templates for later replay and training.",
    responsibilities: [
      "Record timestamped events and evidence",
      "Produce run summaries",
      "Maintain reusable workflow templates",
    ],
    inputs: ["run events", "frames", "audio transcripts", "judgments"],
    outputs: ["run record", "summary", "export manifest"],
    implementationStatus: "partial",
    currentImplementation: ["Kitchen run events", "frame persistence", "Gemini Live recordings"],
    gaps: ["No unified session schema across agents", "No template library", "No export manifest tied to training eval"],
  },
  {
    id: "training-eval",
    name: "Training / Evaluation Agent",
    lane: "training_eval",
    purpose: "Turn captured runs into baseline metrics, supervised data, reward signals, and re-evaluation reports.",
    responsibilities: [
      "Build baseline eval sets",
      "Create teacher/student pairs",
      "Track before/after model performance",
    ],
    inputs: ["run exports", "teacher labels", "student outputs", "reward rubric"],
    outputs: ["metrics", "dataset manifest", "training report"],
    implementationStatus: "partial",
    currentImplementation: ["Supervision pair store", "sibling training repo hooks", "normalized demo manifests"],
    gaps: ["No one-click export/import bridge", "No reward rubric in dashboard", "No completed SFT/GRPO loop artifact"],
  },
];

export function getAgentRole(id: string) {
  return LABOS_AGENT_ROLES.find((role) => role.id === id);
}
