import type { ToolCapability } from "./types.js";

export const LABOS_TOOL_OCEAN: ToolCapability[] = [
  {
    id: "ai.provider-routing",
    name: "Provider-routed multimodal inference",
    ownerAgent: "developer",
    lane: "cross_cutting",
    status: "available",
    description: "Routes model IDs through LabOS inference providers.",
    module: "dashboard/src/server/ai/labos-inference.ts",
    gaps: ["No durable per-agent tool-call trace yet"],
  },
  {
    id: "physical.frame-capture",
    name: "Glasses frame capture",
    ownerAgent: "perception",
    lane: "physical_lab",
    status: "available",
    description: "Captures latest MJPEG frame or falls back to /api/preview/frame.",
    route: "/api/preview/frame",
    module: "dashboard/src/server/ai/frame-analyzer.ts",
    gaps: ["Needs continuous validation scheduler and session-linked frame buffer"],
  },
  {
    id: "physical.multiscale-validation",
    name: "Protocol-aware multiscale validation",
    ownerAgent: "perception",
    lane: "physical_lab",
    status: "partial",
    description: "Plans and executes frame, short-chunk, step-window, and session checks for protocol adherence.",
    route: "/api/kitchen/validation/*",
    module: "dashboard/src/server/ai/kitchen/multiscale-validation.ts",
    gaps: ["WIP foundation only; not yet wired to continuous realtime loop"],
  },
  {
    id: "physical.protocol-tracker",
    name: "Kitchen protocol tracker",
    ownerAgent: "protocol",
    lane: "physical_lab",
    status: "available",
    description: "Tracks setup/running/completed protocol state and step advancement.",
    route: "/api/kitchen/run/*",
    module: "dashboard/src/server/ai/kitchen/tracker.ts",
    gaps: ["Needs agent-owned adherence/recovery policy"],
  },
  {
    id: "physical.gemini-live-coach",
    name: "Gemini Live voice coach",
    ownerAgent: "documentarian",
    lane: "physical_lab",
    status: "available",
    description: "Streams glasses microphone/audio and low-rate video frames to Gemini Live for conversational guidance.",
    route: "/api/live-coach/*",
    module: "dashboard/src/server/live-coach/live-coach.ts",
    gaps: ["Semantic scene understanding is soft context; deterministic pass/fail still belongs to adherence tools"],
  },
  {
    id: "physical.perception-runtime-registry",
    name: "Perception runtime registry",
    ownerAgent: "perception",
    lane: "physical_lab",
    status: "partial",
    description: "Catalogs Gemini Live, segmentation, LabClaw vision skills, and B3D as pluggable perception primitives.",
    route: "/api/perception/runtime",
    module: "dashboard/src/server/ai/perception/runtimes.ts",
    gaps: ["RunPod-hosted LabClaw/B3D adapters are specified but not implemented yet"],
  },
  {
    id: "training.supervision-pairs",
    name: "Teacher/student supervision pair store",
    ownerAgent: "training-eval",
    lane: "training_eval",
    status: "partial",
    description: "Stores frame-level teacher/student comparisons for model improvement.",
    route: "/api/kitchen/teacher/student/compare",
    module: "dashboard/src/server/ai/supervision-store.ts",
    gaps: ["Needs normalized run/session export manifest and reward schema"],
  },
  {
    id: "digital.labclaw-skill-browser",
    name: "LabClaw skill browser",
    ownerAgent: "toolsmith",
    lane: "digital_lab",
    status: "partial",
    description: "Indexes and previews local LabClaw skills for grounded planning.",
    route: "/api/labclaw/*",
    module: "dashboard/src/server/routes/labclaw.ts",
    gaps: ["Does not execute or validate generated tools"],
  },
  {
    id: "digital.tool-creation",
    name: "Tool creation and validation loop",
    ownerAgent: "toolsmith",
    lane: "digital_lab",
    status: "missing",
    description: "Paper-style tool creation agent that discovers, tests, and registers new tools.",
    gaps: ["Need sandboxed runner, registry schema, and validation tests"],
  },
];

export function listToolsForAgent(agentId: string) {
  return LABOS_TOOL_OCEAN.filter((tool) => tool.ownerAgent === agentId);
}
