"""
Ollama provider — real implementation.

Talks to a local Ollama server (default http://localhost:11434) through its
native /api/chat endpoint. Multimodal models (e.g. llava, qwen2.5-vl) are
sent the frame as a base64 image alongside the protocol-aware prompt.

The provider speaks OpenLabOS's `JudgmentRequest`/`Judgment` shapes — those
are the wire types the API forwards to us, derived from packages/protocol's
canonical schemas. The Pydantic mirror is regenerated by
`scripts/regenerate-protocol-types.py`; until that codegen lands, we keep a
slim local TypedDict that captures exactly the fields we need.
"""
from __future__ import annotations

import asyncio
import base64
import json
import os
import re
import urllib.request
import urllib.error
from datetime import datetime, timezone
from typing import Any
from uuid import uuid4


class OllamaError(RuntimeError):
    pass


_SYSTEM = (
    "You are OpenLabOS, a closed-world judge. Given one frame of a "
    "laboratory protocol step and the step's structured criteria, return "
    "exactly one JSON object with the schema:\n"
    '  { "verdict": "succeeded"|"in_progress"|"failed"|"indeterminate",'
    '    "rationale": string,'
    '    "criteria": [{"criterion_index": int, "satisfied": bool,'
    '                  "evidence": string}],'
    '    "observed_objects": [{"object_id": string, "confidence": number}] }\n'
    "Do not write anything outside the JSON object. Confidence is in [0, 1]."
)


def _step_prompt(step: dict[str, Any]) -> str:
    title = step.get("title", "")
    instruction = step.get("instruction", "")
    expected = ", ".join(
        f"{o.get('object_id')} ({o.get('label')})"
        for o in step.get("expected_objects", [])
    )
    criteria_lines = []
    for i, c in enumerate(step.get("success_criteria", [])):
        criteria_lines.append(
            f"  {i}. [{c.get('kind')}] {c.get('description', '')}"
        )
    criteria_block = "\n".join(criteria_lines) or "  (none)"
    return (
        f"Step: {title}\n"
        f"Instruction: {instruction}\n"
        f"Expected entities: {expected or '(none specified)'}\n"
        f"Success criteria (indexed):\n{criteria_block}\n\n"
        "Decide a verdict for the step against this single frame and return "
        "the JSON object."
    )


def _strict_json(text: str) -> dict[str, Any]:
    """
    Best-effort extraction of the first JSON object in `text`. Ollama
    occasionally adds a brief trailing comment despite the system prompt.
    """
    text = text.strip()
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass
    match = re.search(r"\{[\s\S]*\}", text)
    if not match:
        raise OllamaError(f"Ollama did not return JSON (got {text[:200]!r})")
    return json.loads(match.group(0))


class OllamaProvider:
    """
    Provider that drives a local Ollama server.

    Args:
        base_url: e.g. ``http://localhost:11434``.
        model: any Ollama model id; for vision use llava, llama3.2-vision,
               qwen2.5vl, etc.
        timeout_s: per-call timeout in seconds.
    """

    def __init__(
        self,
        base_url: str | None = None,
        model: str | None = None,
        timeout_s: float = 30.0,
    ) -> None:
        self.base_url = (
            base_url or os.environ.get("OLLAMA_BASE_URL", "http://localhost:11434")
        ).rstrip("/")
        self.model = model or os.environ.get("OLLAMA_MODEL", "llama3.2-vision")
        self.timeout_s = timeout_s

    async def render_judgment(self, request: dict[str, Any]) -> dict[str, Any]:
        """
        Generate a Judgment for one frame against one step.

        Request shape (mirrors what the API forwards):
            {
              "session_id": str,
              "step": Protocol.Step (dict),
              "frame_uri": str,                  # file://... or https://...
              "frame_b64": str | None,           # optional inline payload
              "context": dict | None,
            }
        """
        step = request["step"]
        frame_b64 = request.get("frame_b64") or _read_frame_b64(request.get("frame_uri"))

        prompt = _step_prompt(step)
        message: dict[str, Any] = {"role": "user", "content": prompt}
        if frame_b64:
            message["images"] = [frame_b64]

        body = json.dumps(
            {
                "model": self.model,
                "messages": [
                    {"role": "system", "content": _SYSTEM},
                    message,
                ],
                "stream": False,
                "format": "json",
                "options": {"temperature": 0.0},
            }
        ).encode("utf-8")

        loop = asyncio.get_event_loop()
        raw = await loop.run_in_executor(None, self._post_chat, body)
        content = raw.get("message", {}).get("content", "")
        parsed = _strict_json(content)

        return {
            "judgment_id": str(uuid4()),
            "session_id": request["session_id"],
            "step_id": step["step_id"],
            "frame_uri": request.get("frame_uri", ""),
            "emitted_at": datetime.now(timezone.utc)
            .isoformat()
            .replace("+00:00", "Z"),
            "source": f"ollama:{self.model}",
            "verdict": parsed.get("verdict", "indeterminate"),
            "rationale": parsed.get("rationale", ""),
            "criteria": parsed.get("criteria", []),
            "observed_objects": parsed.get("observed_objects", []),
        }

    def _post_chat(self, body: bytes) -> dict[str, Any]:
        req = urllib.request.Request(
            f"{self.base_url}/api/chat",
            data=body,
            headers={"content-type": "application/json"},
            method="POST",
        )
        try:
            with urllib.request.urlopen(req, timeout=self.timeout_s) as r:
                return json.loads(r.read().decode("utf-8"))
        except urllib.error.URLError as e:  # pragma: no cover - network path
            raise OllamaError(f"Ollama request failed: {e}") from e


def _read_frame_b64(frame_uri: str | None) -> str | None:
    if not frame_uri:
        return None
    if frame_uri.startswith("file://"):
        path = frame_uri[len("file://") :]
        try:
            with open(path, "rb") as fh:
                return base64.b64encode(fh.read()).decode("ascii")
        except OSError:
            return None
    return None
